name: 'Execute Oc command'
description: 'Execute Oc command to Openshift cluster'
author: 'Red Hat'
inputs:
  version:
    description: 'Choose the oc version you want to use to execute the command. It can be a version or an url where to download oc cli desired. If left blank latest oc cli will be used.'
    default: 'latest'
  openshift_server_url:
    description: 'The URL of the Openshift cluster'
  parameters:
    description: 'JSON with values to connect to the Openshift cluster'
  args:
    description: 'Oc command to be executed'
runs:
  using: 'node12'
  main: '../lib/src/ocExec.js'